bcc: null
cc: null
enabled: true
language: orderLanguage
name: Bestell-Best√§tigung
plainTextTemplatePath: ''
recipientType: customer
replyTo: bestellung@terra-verde.ch
subject: 'Ihre Bestellung bei TERRA VERDE Bio-Gourmet AG - Nr.{{ order.reference }}'
templatePath: /shop/_email/order-confirmation.twig
to: null
