defaultPlacement: end
enableVersioning: true
handle: agb
name: AGB
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Prim√§re eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    enabledByDefault: true
    hasUrls: true
    template: _pages/agb/index
    uriFormat: '{slug}'
type: single
