defaultPlacement: end
enableVersioning: true
handle: newStructure
name: Neues
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Prim√§re eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    enabledByDefault: true
    hasUrls: true
    template: _pages/aktuell/entry
    uriFormat: 'aktuell/{slug}'
structure:
  maxLevels: null
  uid: 94c1e190-c7ab-4543-90a9-e7d6cc43a68a
type: structure
